name: build-and-test

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  backend:
    name: Backend (Spring Boot)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: HealthApp-Backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Run tests but disable DB/JPA auto-config
      - name: Build & Test (DB-free)
        env:
          SPRING_AUTOCONFIGURE_EXCLUDE: >
            org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
            org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
          SPRING_SQL_INIT_MODE: never
          SPRING_JPA_HIBERNATE_DDL_AUTO: none
        run: mvn -B verify

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: backend-surefire-reports
          path: HealthApp-Backend/target/surefire-reports

  frontend:
    name: Frontend (Next.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: healthapp-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: healthapp-frontend/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Unit tests
        run: npm test --if-present -- --ci --reporters=default --reporters=jest-junit

      - name: Build
        run: npm run build

      # Upload Jest JUnit results if present
      - name: Upload frontend test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-reports
          path: |
            healthapp-frontend/junit.xml
            healthapp-frontend/test-results/**/*.xml
          if-no-files-found: ignore
